{% set name = "icub-models" %}
{% set version = "1.22.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/icub-models/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9165339b31d1051ada696fd1ec236e06d246863b06c4856d8a86dc3289b2493a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - multisheller


about:
  home: https://github.com/robotology/icub-models
  license: CC-BY-SA-4.0
  license_file: LICENSE
  summary: Official URDF and SDF models of the iCub humanoid robot.

extra:
  recipe-maintainers:
    - traversaro
