{% set name = "icub-models" %}
{% set version = "1.21.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/icub-models/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 508154b0954410e2d9a6609cd6063de2b16699dd7cfedd3d0f904de347c5de02

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - multisheller


about:
  home: https://github.com/robotology/icub-models
  license: CC-BY-SA-4.0
  license_file: LICENSE
  summary: Official URDF and SDF models of the iCub humanoid robot.

extra:
  recipe-maintainers:
    - traversaro
